on:
  workflow_call:
    inputs:
      project_name: 
        required: true
        type: string
      output_dir: 
        required: true
        type: string
      aws_lambda_name: 
        type: string
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          npm ci
          npx nx build ${{ inputs.project_name }}
      - name: bundle
        run: |
          cd ${{ inputs.output_dir }}
          zip -r -X "./bundle.zip" .
      - name: deploy
        run: aws lambda update-function-code --function-name "${{ inputs.aws_lambda_name }}" --zip-file "fileb://bundle.zip"