on:
  workflow_dispatch:
    inputs:
      aws_lambda:
        required: true
        type: choice
        options:
          - cradle-user-management
          - cradle-ws-management
      project_name:
        required: true
        type: choice
        options:
          - services-users
          - services-realtime
      project_output_dir:
        default: dist/apps
        type: string
env:
  aws_region: ap-southeast-1
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_U }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_S }}
          aws-region: ${{ env.aws_region }}
      - name: Build project
        run: |
          npm ci
          npx nx build ${{ github.event.inputs.project_name }} --generatePackageJson --outputPath=${{ github.event.inputs.project_output_dir }}/${{ github.event.inputs.project_name }}
      - name: Bundle then deploy
        run: |
          cd ${{ github.event.inputs.project_output_dir }}/${{ github.event.inputs.project_name }}
          npm i -P tslib
          zip -r -X "./bundle.zip" .
          aws lambda update-function-code --function-name "${{ github.event.inputs.aws_lambda }}" --zip-file "fileb://bundle.zip"
