on:
  workflow_dispatch:
env: 
  aws_region: ap-southeast-1
jobs:
  build-then-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_U }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_S }}
          aws-region: ${{ env.aws_region }}
      - name: build project
        run: |
          npm ci
          npx nx build ${{ inputs.project_name }}
      - name: bundle files
        run: |
          cd ${{ inputs.output_dir }}
          zip -r -X "./bundle.zip" .
      - name: deploy bundle
        run: aws lambda update-function-code --function-name "${{ inputs.aws_lambda_name }}" --zip-file "fileb://bundle.zip"