on:
  workflow_dispatch:
jobs:
  build-then-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/aws-lambda-deploy.yml
        with:
          aws_lambda_name: 'dev-test'
          output_dir: 'dist/apps/services/users'
          project_name: 'services-users'
        secrets: 
          AWS_ACCESS_U: ${{ secrets.AWS_ACCESS_U }}
          AWS_ACCESS_S: ${{ secrets.AWS_ACCESS_S }}
          BLUBBERFISH: ${{ secrets.BLUBBERFISH }}